pipeline {
    agent{
		label 'corbinThesis'
	}

    stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}
		stage('Restore') {
            steps {
                // bat 'dotnet restore ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln'
				bat 'nuget restore ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln'
            }
        }
        stage('Build') {
            steps {
				bat 'dotnet msbuild ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln /t:Rebuild /p:Configuration=Release'
            }
        }
        stage('Test') {
            steps {
                bat 'dotnet test ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"'
            }
			post {
                always {
                    mstest testResultsFile: "test_results.trx/*.trx", keepLongStdio: true
                }
            }

        }
    }
}