pipeline {
    agent{
		label 'corbinThesis'
	}

    stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}
		stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }
        stage('Build') {
            steps {
				sh 'dotnet build --configuration Release --no-restore'
            }
        }
        stage('Test') {
            steps {
                sh 'dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"'
            }
			post {
                always {
                    mstest testResultsFile: "test_results.trx/*.trx", keepLongStdio: true
                }
            }

        }
    }
}