pipeline {
    agent{
		label 'corbinThesis'
	}

    stages {
		stage('Checkout') {
			steps {
				checkout scm
			}
		}
		stage('Restore') {
            steps {
                // bat 'dotnet restore ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln'
				bat 'nuget restore ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln'
            }
        }
        stage('Build') {
            steps {
				bat 'dotnet msbuild ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln /t:Rebuild /p:Configuration=Release'
            }
        }
        stage('Test') {
            steps {
                bat 'dotnet test ./CodeProjects/L5XAutomationToolTests/L5XAutomationToolTests.csproj --configuration Release --no-build --no-restore --logger "trx;LogFileName=TestResults.trx"'
            }
			post {
                always {
                    mstest(testResultsFile: "./CodeProjects/JenkinsResults/test_results.trx", keepLongStdio: true)
                }
            }

        }
    }
}