<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
	</PropertyGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="L5XAutomationToolTests" />
	</ItemGroup>
	
</Project>
