pipeline {
    agent{
		label params.CUSTOM_NODE ?: params.NODE
	}
    stages {
		stage('Checkout') {
			steps {
				cleanWs()
				checkout scm
			}
		}
		stage('Restore') {
            steps {
				 bat 'dotnet restore ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln'
				 bat 'dotnet restore ./CodeProjects/L5XAutomationToolTests/L5XAutomationToolTests.csproj'
            }
        }
        stage('Build') {
            steps {
				bat 'dotnet build ./CodeProjects/L5XAutomationTool/L5XAutomationToolProject.sln /p:Configuration="Release" /p:Platform="Any CPU" --no-restore'
            }
        }
        stage('Test') {
            steps {
				bat 'dotnet test ./CodeProjects/L5XAutomationToolTests/L5XAutomationToolTests.csproj --configuration Release --logger "trx;logfilename=mytests.trx" --no-build --no-restore --results-directory ./CodeProjects/TestResults || exit /b 0'
            }
			post {
                always {
                    mstest(testResultsFile: "CodeProjects/TestResults/*.trx", keepLongStdio: true, failOnError: false)
                }
            }
        }
    }
}