<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>L5XAutomationTool</AssemblyName>
    <RootNamespace>L5XAutomationTool</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <StartupObject>L5XAutomationTool.Program</StartupObject>
  </PropertyGroup>
</Project>