<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	  <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
	<ItemGroup>
    <Compile Remove="L5XFiles\**" />
    <EmbeddedResource Remove="L5XFiles\**" />
    <None Remove="L5XFiles\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FlaUI.UIA2" Version="5.0.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest" Version="4.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\L5XAutomationTool\L5XAutomationTool.csproj" />
  </ItemGroup>
</Project>